//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Artist
{
    public Artist()
    {
        this.Genres = new HashSet<Genre>();
        this.Fans = new HashSet<Fan>();
    }

    public int ArtistKey { get; set; }
    public string ArtistName { get; set; }
    public string ArtistEmail { get; set; }
    public string ArtistWebPage { get; set; }
    public Nullable<System.DateTime> ArtistDateEntered { get; set; }

    public virtual ICollection<Genre> Genres { get; set; }
    public virtual ICollection<Fan> Fans { get; set; }
}

public partial class Fan
{
    public Fan()
    {
        this.Artists = new HashSet<Artist>();
        this.Genres = new HashSet<Genre>();
    }

    public int FanKey { get; set; }
    public string FanName { get; set; }
    public string FanEmail { get; set; }
    public Nullable<System.DateTime> FanDateEntered { get; set; }

    public virtual ICollection<Artist> Artists { get; set; }
    public virtual ICollection<Genre> Genres { get; set; }
}

public partial class Genre
{
    public Genre()
    {
        this.Artists = new HashSet<Artist>();
        this.Fans = new HashSet<Fan>();
    }

    public int GenreKey { get; set; }
    public string GenreName { get; set; }
    public string GenreDescription { get; set; }

    public virtual ICollection<Artist> Artists { get; set; }
    public virtual ICollection<Fan> Fans { get; set; }
}
